modLoader="javafml" 
loaderVersion="[28,)"
issueTrackerURL="https://github.com/VsnGamer/ElevatorMod/issues/"
logoFile="logo.png"
[[mods]]
modId="elevatorid"
version="${file.jarVersion}"
displayName="Elevator Mod"
#updateJSONURL="http://myurl.me/"
displayURL="https://minecraft.curseforge.com/projects/openblocks-elevator/"
credits="OpenBlocks Team"
authors="VsnGamer"
description='''
Simple port of the elevator from OpenBlocks to 1.8+
'''
[[dependencies.elevatorid]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elevatorid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"