modLoader="javafml" 
loaderVersion="[25,)"
issueTrackerURL="https://github.com/VsnGamer/ElevatorMod/issues/" 
displayURL="https://minecraft.curseforge.com/projects/openblocks-elevator/" 
logoFile="examplemod.png" 
credits="OpenBlocks Team" 
authors="VsnGamer" 
[[mods]] 
modId="elevatorid" 
version="${file.jarVersion}" 
displayName="Elevator Mod" 
#updateJSONURL="http://myurl.me/" 
description='''
Simple port of the elevator from OpenBlocks to 1.8+
'''

## A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
#[[dependencies.examplemod]] 
#    # the modid of the dependency
#    modId="forge" 
#    # Does this dependency have to exist - if not, ordering below must be specified
#    mandatory=true 
#    # The version range of the dependency
#    versionRange="[25,)" 
#    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
#    ordering="NONE"
#    # Side this dependency is applied on - BOTH, CLIENT or SERVER
#    side="BOTH"
## Here's another dependency
#[[dependencies.examplemod]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.13.2]"
#    ordering="NONE"
#    side="BOTH"